server:
  addr: "0.0.0.0:8082"
  app_env: development

etcd:
  namespace: "echoapp/"
  endpoints:
    - "127.0.0.1:2379"
  username: root
  password: 123456

asset:
  public_root: ""
  version: "dev"
  view_root: "./resources/views"
  area_root: "./resources/storage/areas"
  public_host: ""

logging:
  formatter: "json"
  level: "debug"

database:
  options:
    - name: echoapp
      driver: mysql
      dsn: "root:pwd@tcp(127.0.0.1:3306)/echoapp?timeout=3s&charset=utf8&parseTime=True&loc=Local"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  pool_size: 15

sms_tokens:
  echoapp:
    access_key: ''
    access_secret: ''
    sign_name: 'xxx'
    template_code: 'SMS_197752288'

rabbit_mq:
  xyt:
    url: 'amqp://{username}:{password}@localhost:5672/{vhost}'

tongcheng:
  notify_url: "http://www.lvcang.cn/jingqu/OpenAPI/OpenService/Scenery"
  client_map:
    1:
      access_key: 'LTAIuxzW62YjGhY1'
      access_secret: 'jTKscagoOE6vWWiVSVIlkLI49bULaT'

report_tickets:
  xyt:
    com_id: 1
    app_key: ''
    base_url: 'https://bigd.tourage.cn'
    scenic_code: ''

jws:
   audience: "user"
   issuer: "xytschool"
   #7天
   timeout: 604800
   public_key_path: "./resources/storage/keys/jws_public_key.pem"
   private_key_path: "./resources/storage/keys/jws_private_key.pem"
   hash_ids_salt: ""

resource:
   base_url: "http://img.xytschool.com"
   cnd_host: "http://img.xytschool.com"
   bucket_name: "image"
   max_file_size: 20000000
   callback_url: "http://goods.api.xyt.com/v1/goods-api/uploadCallback"
   access_key: ""
   secret_key: ""