apiVersion: v1
kind: Service
metadata:
  name: site
  namespace: echoapp
spec:
  selector:
    app: site
  ports:
  - name: "site-8889"
    #nodePort: 32209
    port: 80
    protocol: "TCP"
    targetPort: 8889
  type: "NodePort"
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "site-deploy"
  namespace: "echoapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "site"
  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: "site"
    spec:
      imagePullSecrets:
      - name: gdocker
      containers:
      - name: "site-service"
        image: registry.cn-beijing.aliyuncs.com/gapi/echoapp:latest
        args:
        - "site"
        - "--config-type=apollo"
        command:
        - "echoapp"
        imagePullPolicy: "Always"
        resources: {}
        workingDir: "/usr/local/var/echoapp"
        envFrom:
          - configMapRef:
              name: cm-echoapp-env

      hostAliases:
      - hostnames:
        - "sh2"
        ip: "124.70.157.82"
    
#      affinity:
#         nodeAffinity:
#                 preferredDuringSchedulingIgnoredDuringExecution:
#                 - weight: 90
#                   preference: {}
#                 requiredDuringSchedulingIgnoredDuringExecution:
#                   nodeSelectorTerms:
#                   - matchExpressions:
#                     - key: "kubernetes.io/hostname"
#                       operator: "In"
#                       values:
#                        - "k8s-node1"
#                        - "k8s-node02"
                             
      
