// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/gw123/echo-app/gather/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GatherSalesVolumesEndpoint   endpoint.Endpoint
	GatherCommentsNumberEndpoint endpoint.Endpoint
	GatherViewsEndpoint          endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.GatherService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		GatherCommentsNumberEndpoint: MakeGatherCommentsNumberEndpoint(s),
		GatherSalesVolumesEndpoint:   MakeGatherSalesVolumesEndpoint(s),
		GatherViewsEndpoint:          MakeGatherViewsEndpoint(s),
	}
	for _, m := range mdw["GatherSalesVolumes"] {
		eps.GatherSalesVolumesEndpoint = m(eps.GatherSalesVolumesEndpoint)
	}
	for _, m := range mdw["GatherCommentsNumber"] {
		eps.GatherCommentsNumberEndpoint = m(eps.GatherCommentsNumberEndpoint)
	}
	for _, m := range mdw["GatherViews"] {
		eps.GatherViewsEndpoint = m(eps.GatherViewsEndpoint)
	}
	return eps
}
