// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "github.com/gw123/echo-app/gather/pkg/endpoint"
	service "github.com/gw123/echo-app/gather/pkg/service"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initGRPCHandler(endpoints, g)
	return g
}
func defaultGRPCOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]grpc.ServerOption {
	options := map[string][]grpc.ServerOption{
		"GatherCommentsNumber": {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "GatherCommentsNumber", logger))},
		"GatherSalesVolumes":   {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "GatherSalesVolumes", logger))},
		"GatherViews":          {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "GatherViews", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["GatherSalesVolumes"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GatherSalesVolumes")), endpoint.InstrumentingMiddleware(duration.With("method", "GatherSalesVolumes"))}
	mw["GatherCommentsNumber"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GatherCommentsNumber")), endpoint.InstrumentingMiddleware(duration.With("method", "GatherCommentsNumber"))}
	mw["GatherViews"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GatherViews")), endpoint.InstrumentingMiddleware(duration.With("method", "GatherViews"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"GatherSalesVolumes", "GatherCommentsNumber", "GatherViews"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
