// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gather.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GatherSalesVolumesRequest struct {
	TargetID             int64    `protobuf:"varint,1,opt,name=targetID,proto3" json:"targetID"`
	StartTime            string   `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime"`
	EndTime              string   `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatherSalesVolumesRequest) Reset()         { *m = GatherSalesVolumesRequest{} }
func (m *GatherSalesVolumesRequest) String() string { return proto.CompactTextString(m) }
func (*GatherSalesVolumesRequest) ProtoMessage()    {}
func (*GatherSalesVolumesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee5809ab7d1883a, []int{0}
}

func (m *GatherSalesVolumesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatherSalesVolumesRequest.Unmarshal(m, b)
}
func (m *GatherSalesVolumesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatherSalesVolumesRequest.Marshal(b, m, deterministic)
}
func (m *GatherSalesVolumesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatherSalesVolumesRequest.Merge(m, src)
}
func (m *GatherSalesVolumesRequest) XXX_Size() int {
	return xxx_messageInfo_GatherSalesVolumesRequest.Size(m)
}
func (m *GatherSalesVolumesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GatherSalesVolumesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GatherSalesVolumesRequest proto.InternalMessageInfo

func (m *GatherSalesVolumesRequest) GetTargetID() int64 {
	if m != nil {
		return m.TargetID
	}
	return 0
}

func (m *GatherSalesVolumesRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GatherSalesVolumesRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type GatherSalesVolumesResult struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatherSalesVolumesResult) Reset()         { *m = GatherSalesVolumesResult{} }
func (m *GatherSalesVolumesResult) String() string { return proto.CompactTextString(m) }
func (*GatherSalesVolumesResult) ProtoMessage()    {}
func (*GatherSalesVolumesResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee5809ab7d1883a, []int{1}
}

func (m *GatherSalesVolumesResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatherSalesVolumesResult.Unmarshal(m, b)
}
func (m *GatherSalesVolumesResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatherSalesVolumesResult.Marshal(b, m, deterministic)
}
func (m *GatherSalesVolumesResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatherSalesVolumesResult.Merge(m, src)
}
func (m *GatherSalesVolumesResult) XXX_Size() int {
	return xxx_messageInfo_GatherSalesVolumesResult.Size(m)
}
func (m *GatherSalesVolumesResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GatherSalesVolumesResult.DiscardUnknown(m)
}

var xxx_messageInfo_GatherSalesVolumesResult proto.InternalMessageInfo

func (m *GatherSalesVolumesResult) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GatherSalesVolumesReply struct {
	Result               *GatherSalesVolumesResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	Code                 int64                     `protobuf:"varint,2,opt,name=code,proto3" json:"code"`
	Message              string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GatherSalesVolumesReply) Reset()         { *m = GatherSalesVolumesReply{} }
func (m *GatherSalesVolumesReply) String() string { return proto.CompactTextString(m) }
func (*GatherSalesVolumesReply) ProtoMessage()    {}
func (*GatherSalesVolumesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee5809ab7d1883a, []int{2}
}

func (m *GatherSalesVolumesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatherSalesVolumesReply.Unmarshal(m, b)
}
func (m *GatherSalesVolumesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatherSalesVolumesReply.Marshal(b, m, deterministic)
}
func (m *GatherSalesVolumesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatherSalesVolumesReply.Merge(m, src)
}
func (m *GatherSalesVolumesReply) XXX_Size() int {
	return xxx_messageInfo_GatherSalesVolumesReply.Size(m)
}
func (m *GatherSalesVolumesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GatherSalesVolumesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GatherSalesVolumesReply proto.InternalMessageInfo

func (m *GatherSalesVolumesReply) GetResult() *GatherSalesVolumesResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GatherSalesVolumesReply) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GatherSalesVolumesReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GatherCommentsNumberRequest struct {
	TargetID             int64    `protobuf:"varint,1,opt,name=targetID,proto3" json:"targetID"`
	StartTime            string   `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime"`
	EndTime              string   `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatherCommentsNumberRequest) Reset()         { *m = GatherCommentsNumberRequest{} }
func (m *GatherCommentsNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GatherCommentsNumberRequest) ProtoMessage()    {}
func (*GatherCommentsNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee5809ab7d1883a, []int{3}
}

func (m *GatherCommentsNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatherCommentsNumberRequest.Unmarshal(m, b)
}
func (m *GatherCommentsNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatherCommentsNumberRequest.Marshal(b, m, deterministic)
}
func (m *GatherCommentsNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatherCommentsNumberRequest.Merge(m, src)
}
func (m *GatherCommentsNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GatherCommentsNumberRequest.Size(m)
}
func (m *GatherCommentsNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GatherCommentsNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GatherCommentsNumberRequest proto.InternalMessageInfo

func (m *GatherCommentsNumberRequest) GetTargetID() int64 {
	if m != nil {
		return m.TargetID
	}
	return 0
}

func (m *GatherCommentsNumberRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GatherCommentsNumberRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type GatherCommentsNumberResult struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatherCommentsNumberResult) Reset()         { *m = GatherCommentsNumberResult{} }
func (m *GatherCommentsNumberResult) String() string { return proto.CompactTextString(m) }
func (*GatherCommentsNumberResult) ProtoMessage()    {}
func (*GatherCommentsNumberResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee5809ab7d1883a, []int{4}
}

func (m *GatherCommentsNumberResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatherCommentsNumberResult.Unmarshal(m, b)
}
func (m *GatherCommentsNumberResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatherCommentsNumberResult.Marshal(b, m, deterministic)
}
func (m *GatherCommentsNumberResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatherCommentsNumberResult.Merge(m, src)
}
func (m *GatherCommentsNumberResult) XXX_Size() int {
	return xxx_messageInfo_GatherCommentsNumberResult.Size(m)
}
func (m *GatherCommentsNumberResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GatherCommentsNumberResult.DiscardUnknown(m)
}

var xxx_messageInfo_GatherCommentsNumberResult proto.InternalMessageInfo

func (m *GatherCommentsNumberResult) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GatherCommentsNumberReply struct {
	Result               *GatherCommentsNumberResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	Code                 int64                       `protobuf:"varint,2,opt,name=code,proto3" json:"code"`
	Message              string                      `protobuf:"bytes,3,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GatherCommentsNumberReply) Reset()         { *m = GatherCommentsNumberReply{} }
func (m *GatherCommentsNumberReply) String() string { return proto.CompactTextString(m) }
func (*GatherCommentsNumberReply) ProtoMessage()    {}
func (*GatherCommentsNumberReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee5809ab7d1883a, []int{5}
}

func (m *GatherCommentsNumberReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatherCommentsNumberReply.Unmarshal(m, b)
}
func (m *GatherCommentsNumberReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatherCommentsNumberReply.Marshal(b, m, deterministic)
}
func (m *GatherCommentsNumberReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatherCommentsNumberReply.Merge(m, src)
}
func (m *GatherCommentsNumberReply) XXX_Size() int {
	return xxx_messageInfo_GatherCommentsNumberReply.Size(m)
}
func (m *GatherCommentsNumberReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GatherCommentsNumberReply.DiscardUnknown(m)
}

var xxx_messageInfo_GatherCommentsNumberReply proto.InternalMessageInfo

func (m *GatherCommentsNumberReply) GetResult() *GatherCommentsNumberResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GatherCommentsNumberReply) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GatherCommentsNumberReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GatherViewsRequest struct {
	TargetID             int64    `protobuf:"varint,1,opt,name=targetID,proto3" json:"targetID"`
	StartTime            string   `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime"`
	EndTime              string   `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatherViewsRequest) Reset()         { *m = GatherViewsRequest{} }
func (m *GatherViewsRequest) String() string { return proto.CompactTextString(m) }
func (*GatherViewsRequest) ProtoMessage()    {}
func (*GatherViewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee5809ab7d1883a, []int{6}
}

func (m *GatherViewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatherViewsRequest.Unmarshal(m, b)
}
func (m *GatherViewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatherViewsRequest.Marshal(b, m, deterministic)
}
func (m *GatherViewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatherViewsRequest.Merge(m, src)
}
func (m *GatherViewsRequest) XXX_Size() int {
	return xxx_messageInfo_GatherViewsRequest.Size(m)
}
func (m *GatherViewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GatherViewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GatherViewsRequest proto.InternalMessageInfo

func (m *GatherViewsRequest) GetTargetID() int64 {
	if m != nil {
		return m.TargetID
	}
	return 0
}

func (m *GatherViewsRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GatherViewsRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type GatherViewsResult struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatherViewsResult) Reset()         { *m = GatherViewsResult{} }
func (m *GatherViewsResult) String() string { return proto.CompactTextString(m) }
func (*GatherViewsResult) ProtoMessage()    {}
func (*GatherViewsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee5809ab7d1883a, []int{7}
}

func (m *GatherViewsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatherViewsResult.Unmarshal(m, b)
}
func (m *GatherViewsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatherViewsResult.Marshal(b, m, deterministic)
}
func (m *GatherViewsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatherViewsResult.Merge(m, src)
}
func (m *GatherViewsResult) XXX_Size() int {
	return xxx_messageInfo_GatherViewsResult.Size(m)
}
func (m *GatherViewsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GatherViewsResult.DiscardUnknown(m)
}

var xxx_messageInfo_GatherViewsResult proto.InternalMessageInfo

func (m *GatherViewsResult) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GatherViewsReply struct {
	Result               *GatherViewsResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	Code                 int64              `protobuf:"varint,2,opt,name=code,proto3" json:"code"`
	Message              string             `protobuf:"bytes,3,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GatherViewsReply) Reset()         { *m = GatherViewsReply{} }
func (m *GatherViewsReply) String() string { return proto.CompactTextString(m) }
func (*GatherViewsReply) ProtoMessage()    {}
func (*GatherViewsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee5809ab7d1883a, []int{8}
}

func (m *GatherViewsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatherViewsReply.Unmarshal(m, b)
}
func (m *GatherViewsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatherViewsReply.Marshal(b, m, deterministic)
}
func (m *GatherViewsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatherViewsReply.Merge(m, src)
}
func (m *GatherViewsReply) XXX_Size() int {
	return xxx_messageInfo_GatherViewsReply.Size(m)
}
func (m *GatherViewsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GatherViewsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GatherViewsReply proto.InternalMessageInfo

func (m *GatherViewsReply) GetResult() *GatherViewsResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GatherViewsReply) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GatherViewsReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GatherSalesVolumesRequest)(nil), "pb.GatherSalesVolumesRequest")
	proto.RegisterType((*GatherSalesVolumesResult)(nil), "pb.GatherSalesVolumesResult")
	proto.RegisterType((*GatherSalesVolumesReply)(nil), "pb.GatherSalesVolumesReply")
	proto.RegisterType((*GatherCommentsNumberRequest)(nil), "pb.GatherCommentsNumberRequest")
	proto.RegisterType((*GatherCommentsNumberResult)(nil), "pb.GatherCommentsNumberResult")
	proto.RegisterType((*GatherCommentsNumberReply)(nil), "pb.GatherCommentsNumberReply")
	proto.RegisterType((*GatherViewsRequest)(nil), "pb.GatherViewsRequest")
	proto.RegisterType((*GatherViewsResult)(nil), "pb.GatherViewsResult")
	proto.RegisterType((*GatherViewsReply)(nil), "pb.GatherViewsReply")
}

func init() { proto.RegisterFile("gather.proto", fileDescriptor_3ee5809ab7d1883a) }

var fileDescriptor_3ee5809ab7d1883a = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0xaa, 0xda, 0x40,
	0x14, 0xc6, 0x49, 0x52, 0x6c, 0x3d, 0xba, 0xd0, 0xa9, 0xd6, 0x34, 0xfe, 0xa9, 0x0c, 0x14, 0x44,
	0xda, 0x04, 0x6c, 0xe9, 0xc2, 0x6d, 0x0b, 0xa5, 0x9b, 0x2e, 0x52, 0x71, 0x3f, 0xa9, 0x43, 0x0c,
	0x24, 0x99, 0x38, 0x33, 0xa1, 0x75, 0xd1, 0x45, 0xef, 0x2b, 0xdc, 0xe7, 0xba, 0xab, 0xfb, 0x0a,
	0xf7, 0x41, 0x2e, 0x99, 0xf8, 0x27, 0x6a, 0xb2, 0x11, 0xdc, 0x65, 0xe6, 0x7c, 0xf3, 0x7d, 0x87,
	0xdf, 0x39, 0x04, 0x9a, 0x3e, 0x91, 0x6b, 0xca, 0xed, 0x84, 0x33, 0xc9, 0x90, 0x9e, 0x78, 0xd6,
	0xc0, 0x67, 0xcc, 0x0f, 0xa9, 0x43, 0x92, 0xc0, 0x21, 0x71, 0xcc, 0x24, 0x91, 0x01, 0x8b, 0x45,
	0xae, 0xc0, 0x0c, 0xde, 0x7e, 0x57, 0x2f, 0x7e, 0x91, 0x90, 0x8a, 0x25, 0x0b, 0xd3, 0x88, 0x0a,
	0x97, 0x6e, 0x52, 0x2a, 0x24, 0xb2, 0xe0, 0x95, 0x24, 0xdc, 0xa7, 0xf2, 0xc7, 0x37, 0x53, 0x1b,
	0x6b, 0x13, 0xc3, 0x3d, 0x9c, 0xd1, 0x00, 0xea, 0x42, 0x12, 0x2e, 0x17, 0x41, 0x44, 0x4d, 0x7d,
	0xac, 0x4d, 0xea, 0xee, 0xf1, 0x02, 0x99, 0xf0, 0x92, 0xc6, 0x2b, 0x55, 0x33, 0x54, 0x6d, 0x7f,
	0xc4, 0x1f, 0xc0, 0x2c, 0x0b, 0x14, 0x69, 0x28, 0x51, 0x0b, 0x8c, 0x38, 0x8d, 0x76, 0x51, 0xd9,
	0x27, 0xfe, 0x07, 0xbd, 0x32, 0x75, 0x12, 0x6e, 0xd1, 0x67, 0xa8, 0x71, 0xf5, 0x4c, 0xe9, 0x1b,
	0xb3, 0x81, 0x9d, 0x78, 0x76, 0x95, 0xb5, 0xbb, 0xd3, 0x22, 0x04, 0x2f, 0x7e, 0xb3, 0x55, 0xde,
	0xb1, 0xe1, 0xaa, 0xef, 0xac, 0xd9, 0x88, 0x0a, 0x41, 0xfc, 0x43, 0xb3, 0xbb, 0x23, 0xde, 0x40,
	0x3f, 0x77, 0xfc, 0xca, 0xa2, 0x88, 0xc6, 0x52, 0xfc, 0x4c, 0x23, 0x8f, 0xf2, 0x5b, 0xf2, 0xb1,
	0xc1, 0x2a, 0x8f, 0xac, 0x20, 0xf4, 0x5f, 0xdb, 0x4f, 0xf0, 0xfc, 0x41, 0x06, 0xe9, 0xcb, 0x19,
	0xa4, 0xd1, 0x11, 0x52, 0x99, 0xff, 0x95, 0x98, 0xd6, 0x80, 0x72, 0xcf, 0x65, 0x40, 0xff, 0xdc,
	0x74, 0x7b, 0xde, 0x43, 0xfb, 0x24, 0xa9, 0x02, 0x0a, 0x83, 0xd6, 0x89, 0x2c, 0x43, 0xf1, 0xf1,
	0x0c, 0x45, 0xf7, 0x88, 0xa2, 0x60, 0x76, 0x1d, 0x81, 0xd9, 0x83, 0x0e, 0xf5, 0xdc, 0x8b, 0x73,
	0x8e, 0x92, 0x3d, 0x8f, 0xe2, 0x22, 0xa2, 0x61, 0xd5, 0x82, 0x2a, 0x5c, 0x56, 0xbf, 0xaa, 0x9c,
	0x84, 0x5b, 0x3c, 0xba, 0x7b, 0x7c, 0xba, 0xd7, 0x4d, 0xfc, 0xda, 0xb9, 0x54, 0xcc, 0xb5, 0x29,
	0xfa, 0x0b, 0x9d, 0xb2, 0xa9, 0xa2, 0x77, 0xd5, 0xf3, 0xce, 0x53, 0x87, 0xd5, 0x82, 0x2c, 0x77,
	0xac, 0x72, 0x2d, 0xdc, 0x75, 0xca, 0x34, 0x59, 0xf2, 0x02, 0x1a, 0x05, 0x88, 0xe8, 0xcd, 0x05,
	0xd5, 0x3c, 0xa7, 0x73, 0x71, 0x9f, 0xd9, 0xf7, 0x94, 0x7d, 0x1b, 0x37, 0x9d, 0x42, 0x69, 0xae,
	0x4d, 0xbd, 0x9a, 0xfa, 0x3b, 0x7d, 0x7a, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xea, 0xe6, 0x65, 0xaa,
	0xcf, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatherrrrClient is the client API for Gatherrrr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatherrrrClient interface {
	GatherSalesVolumes(ctx context.Context, in *GatherSalesVolumesRequest, opts ...grpc.CallOption) (*GatherSalesVolumesReply, error)
	GatherCommentsNumber(ctx context.Context, in *GatherCommentsNumberRequest, opts ...grpc.CallOption) (*GatherCommentsNumberReply, error)
	GatherViews(ctx context.Context, in *GatherViewsRequest, opts ...grpc.CallOption) (*GatherViewsReply, error)
}

type gatherrrrClient struct {
	cc *grpc.ClientConn
}

func NewGatherrrrClient(cc *grpc.ClientConn) GatherrrrClient {
	return &gatherrrrClient{cc}
}

func (c *gatherrrrClient) GatherSalesVolumes(ctx context.Context, in *GatherSalesVolumesRequest, opts ...grpc.CallOption) (*GatherSalesVolumesReply, error) {
	out := new(GatherSalesVolumesReply)
	err := c.cc.Invoke(ctx, "/pb.Gatherrrr/GatherSalesVolumes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatherrrrClient) GatherCommentsNumber(ctx context.Context, in *GatherCommentsNumberRequest, opts ...grpc.CallOption) (*GatherCommentsNumberReply, error) {
	out := new(GatherCommentsNumberReply)
	err := c.cc.Invoke(ctx, "/pb.Gatherrrr/GatherCommentsNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatherrrrClient) GatherViews(ctx context.Context, in *GatherViewsRequest, opts ...grpc.CallOption) (*GatherViewsReply, error) {
	out := new(GatherViewsReply)
	err := c.cc.Invoke(ctx, "/pb.Gatherrrr/GatherViews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatherServer is the server API for Gatherrrr service.
type GatherServer interface {
	GatherSalesVolumes(context.Context, *GatherSalesVolumesRequest) (*GatherSalesVolumesReply, error)
	GatherCommentsNumber(context.Context, *GatherCommentsNumberRequest) (*GatherCommentsNumberReply, error)
	GatherViews(context.Context, *GatherViewsRequest) (*GatherViewsReply, error)
}

func RegisterGatherServer(s *grpc.Server, srv GatherServer) {
	s.RegisterService(&_Gatherrrr_serviceDesc, srv)
}

func _Gatherrrr_GatherSalesVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatherSalesVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatherrrrServer).GatherSalesVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Gatherrrr/GatherSalesVolumes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatherrrrServer).GatherSalesVolumes(ctx, req.(*GatherSalesVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gatherrrr_GatherCommentsNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatherCommentsNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatherrrrServer).GatherCommentsNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Gatherrrr/GatherCommentsNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatherrrrServer).GatherCommentsNumber(ctx, req.(*GatherCommentsNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gatherrrr_GatherViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatherViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatherrrrServer).GatherViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Gatherrrr/GatherViews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatherrrrServer).GatherViews(ctx, req.(*GatherViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gatherrrr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Gatherrrr",
	HandlerType: (*GatherrrrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GatherSalesVolumes",
			Handler:    _Gatherrrr_GatherSalesVolumes_Handler,
		},
		{
			MethodName: "GatherCommentsNumber",
			Handler:    _Gatherrrr_GatherCommentsNumber_Handler,
		},
		{
			MethodName: "GatherViews",
			Handler:    _Gatherrrr_GatherViews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gather.proto",
}
